name: Pruebas Unitarias Acceso Biometrico

on:
  push:
    branches:
      - main
      - gonzalo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Tests con Pytest
      run: |
        pytest src/test_perfil_acceso.py
