          }

    - name: Enviar correo de éxito
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: '✅ Éxito en CI/CD - Merge completado'
        body: 'Las pruebas fueron exitosas y el merge de Maikel a MAIN se completó correctamente.\n\nDetalles del workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: GitHub Actions
        content_type: text/plain

    - name: Desplegar a producción via FTP
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}

