name: Pruebas Python

on:
  push:
    branches:
      - main
      - Gonzalo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Instalar dependencias del sistema para GUI
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 mesa-utils

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Tests con Pytest
      run: |
        pytest src/test_perfil_acceso.py
